cargo-features = ["edition2021"]
[package]
name = "c2proxy"
version = "0.1.0"
edition = "2021"

[lib]
name = "c2proxy"
path = "src/lib.rs"

[[bin]]
name = "c2proxy"
path = "src/c2proxy/main.rs"

[[bin]]
name = "c2proxy_worker"
path = "src/c2proxy_worker/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filecoin-proofs-api = "10.1.0"
clap = { version = "3.0.4", features = ["derive", "env"] }
jsonrpc-core = { version = "18.0.0", features = [] }
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-core-client = {version="18.0.0", features = ["http"]}
log = { version = "0.4", features = ["std"] }
simplelog = "*"
diesel = { version = "1.4.4", features = ["sqlite", "numeric"] }
forest_address = "0.3.2"
num_enum = "0.5.6"
anyhow = "1.0.52"
hex = {version ="0.4.3"}
crossbeam-channel = "0.5.2"
serde_json = { version = "1.0" }
serde = "1.0.133"
chrono = "0.4.19"
crossbeam = "0.8.1"
crossbeam-utils = "0.8.6"
base64 = "0.13.0"
uuid = { version = "0.8", features = ["v4"] }